### ISSUE TITLE
Touchscreen does not work, even with firmware

### ISSUE THREAD

**Issue by LegoLivesMatter** [agreenbhm/android_device_samsung_gta4lwifi#4]
As title says, the addition of firmware did not fix the touchscreen issue. Fixing this would probably require debugging the kernel driver, although this is not an option at the moment as we're still using the prebuilt kernel and I have not yet succeeded at compiling the kernel source.

EDIT: Please do not close, as I intended this issue to be a place to discuss potential fixes for the issue.

**Comment by agreenbhm** [comment]
The touchscreen works for me on my device with a new build that is based on the stock firmware ending in BUF3. I will push that to the repo shortly. See if that fixes things.

**Comment by LegoLivesMatter** [comment]
I see you just pushed the new firmware. However, many of these you do not need because they are for things like GPU acceleration and WiFi, which we don't have in TWRP and Lineage doesn't need them either because this is a Treble device so there is a separate /vendor partition with the firmware and other blobs. Either way, I will rebuild the recovery and report back.

**Comment by agreenbhm** [comment]
I opted to include all firmware files because I wasn't sure exactly what was needed.

**Comment by LegoLivesMatter** [comment]
Just tested and I'm happy to report that the touchscreen does work! Closing.
